# Generated by Django 5.0.6 on 2024-06-21 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 13, 45, 42, 599386)),
        ),
    ]
