# Generated by Django 5.0.6 on 2024-06-21 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todoitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 13, 47, 4, 323090)),
        ),
    ]
